version: '3.8'

services:
  weatherapp:
    build: .
    ports:
      - "80:80"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - weatherdata:/app/data

volumes:
  weatherdata:
